server.port=8080
spring.application.name=apiGateway

# Eureka client config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway manual routes
spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.routes[0].id=resume-service
spring.cloud.gateway.routes[0].uri=lb://resume-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/resume/**

spring.cloud.gateway.routes[1].id=ai-service
spring.cloud.gateway.routes[1].uri=lb://ai-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/ai/**
